# Pattern for Q and A:
# q = "The exception object passed to #raise"
# a = "$!"
def continue?
  print "Enter any key to continue or 'x' to exit: "
  response = gets.chomp().downcase
  if response == 'x'
    return true
  else
    return false
  end
end

question_pool = [
"The exception object passed to #raise.",
"The stack backtrace generated by the last exception raised.",
"Depends on $~. The string matched by the last successful match.",
"Depends on $~. The string to the left of the last successful match.",
"Depends on $~. The string to the right of the last successful match.",
"Depends on $~. The highest group matched by the last successful match.",
"Depends on $~. The Nth group of the last successful match. May be > 1.",
"The MatchData instance of the last match. Thread and scope local. MAGIC",
"The flag for case insensitive. Defaults to nil. Deprecated.",
"The input record separator (eg #gets). Defaults to newline.",
"The output record separator (eg #print and IO#write). Default is nil.",
"The output field separator for the print and Array#join. Defaults to nil.",
"The default separator for String#split. See -F flag.",
"The current line number of the last file from input.",
"Symbol for ARGF.",
"The default output for print, printf. Defaults to $stdout.",
"The last input line of string by gets or readline. Thread and scope local.",
"Contains the name of the script being executed. May be assignable.",
"Symbol for ARGV.",
"The process number of the Ruby running this script. Read only.",
"The status of the last executed child process. Read only. Thread local.",
"Symbol for $LOAD_PATH.",
"The array contains the module names loaded by require.",
"The boolean status of the -d switch.",
"Current input file from ARGF. Same as ARGF.filename.",
"Load path for scripts and binary modules by load or require.",
"The current standard error output.",
"The current standard input.",
"The current standard output.",
"The verbose flag, which is set by the -v switch."
]

answer_pool = [ "$!", "$@", "$&", "$`", "$'", "$+", "$1", "$~", "$=", "$/", "$\\", "$,", "$;", "$.", "$<", "$>", "$_", "$0", "$*", "$$", "$?", "$:", "$\"", "$DEBUG", "$FILENAME", "$LOAD_PATH", "$stderr", "$stdin", "$stdout", "$VERBOSE" ]

puts "*** Test your knowledge of Ruby Globals!***"
puts "Based on Ruby QuickRef from ZenSpider.com"


exit_app = false

while exit_app == false
  #pick a random question
  num = Random.rand(question_pool.length)

  question = question_pool[num]
  answer = answer_pool[num]
  puts ''
  puts "Q: " + question
  print "A: "
  response = gets.chomp()
  if response == answer
    puts "Correct"
  else
    puts "Incorrect. The answer is: #{answer}"
  end

  exit_app = continue?

end